<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner=$block->getProfileDetail();
if ($partner['shop_url']) {
    $sellerId = $partner->getSellerId();
    $analyticStatus = $helper->getAnalyticStatus();
    if ($analyticStatus) {
        $analyticId = $helper->getSellerAnalyticId($sellerId);
    }
    if ($helper->getActiveColorPicker()) { ?>
        <style>
            .page-main{
                background-image:none;
                background-color:<?= $escaper->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php } ?>
    <div class="wk_mp_design">
        <?= $block->getChildHtml("marketplace_seller_top_block")?>
        <?= $block->getChildHtml("marketplace_seller_slider_block")?>
        <div class="wk-mp-collection-container">
            <div class="wk-mp-profile-block" id="about-us">
                <h3 class="wk-mp-aboutus-title wk-mp-description-block-title">
                    <?= $escaper->escapeHtml(__("About Me"))?>
                </h3>
                <h4 class="wk-mp-description-block-subtitle">
                    <?= $escaper->escapeHtml(__("Bio"))?>
                </h4>
                <div class="wk-mp-aboutus-data">
                    <?= /* @noEscape */ $block->getFilterData($partner['about_me']);?>
                    <a href="#" class="wk-mp-aboutus-read-more"><?= $escaper->escapeHtml(__("Read More"))?></a>
                </div>
                <h4 class="wk-mp-description-block-subtitle">
                    <?= $escaper->escapeHtml(__("Training and Awards"))?>
                </h4>
                <div class="wk-mp-aboutus-training">
                    <ul class="page-list">
                        <li>Certificate/Course/Award Name goes here</li>
                        <li>Certificate/Course/Award Name goes here</li>
                        <li>Certificate/Course/Award Name goes here</li>
                        <li>Certificate/Course/Award Name goes here</li>
                        <li>Certificate/Course/Award Name goes here</li>
                        <li>Certificate/Course/Award Name goes here</li>
                    </ul>
                </div>
            </div>
            <div class="wk-mp-profile-block wk-mp-profile-expertise-holder">
                <h3 class="wk-mp-aboutus-title wk-mp-description-block-title">
                    <?= $escaper->escapeHtml(__("Areas of Expertise"))?>
                </h3>
                <div class="wk-mp-profile-expertise-slideshow">
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Accessories</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Athleisure</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Black-Tie</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Business</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Title Goes here</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Title Goes here</h5>
                        </div>
                    </div>
                    <div class="wk-mp-profile-expertise-slide">
                        <div class="wk-mp-profile-expertise-slide-content">
                            <div class="wk-mp-profile-expertise-slide-image">
                                <img src="<?php echo $this->getViewFileUrl('images/expertise.jpg'); ?>" alt="">
                            </div>
                            <h5>Title Goes here</h5>
                        </div>
                    </div>
                </div>
            </div>
            <h3 class="wk-mp-aboutus-title wk-mp-description-block-title">
                <?= $escaper->escapeHtml(__("Client Reviews"))?>
            </h3>
            <div class="wk-mp-profile-block">
                <?= $this->getChildHtml('marketplace_sellerprofile_rating')?>
            </div>
            <?php
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('advice-block-stylist-page')
                    ->toHtml();
            ?>
            <div class="actions centered"><button class="action book-appointment">Book Appointment</button></div>

            <?php if ($helper->getSellerPolicyApproval()) { ?>
                <div class="wk-mp-profile-block" id="wk-mp-policy-block">
                    <div class="wk-mp-policy-block wk-mp-shipping-policy" id="shipping-policy">
                        <div class="wk-mp-policy-block-title">
                            <?= $escaper->escapeHtml(__("Shipping Policy"))?>
                        </div>
                        <div class="wk-mp-policy-block-data">
                            <?= /* @noEscape */ $block->getFilterData($partner['shipping_policy']);?>
                        </div>
                    </div>
                    <div class="wk-mp-policy-block wk-mp-return-policy" id="return-policy">
                        <div class="wk-mp-policy-block-title">
                            <?= /* @noEscape */ __("Return Policy")?>
                        </div>
                        <div class="wk-mp-policy-block-data">
                            <?= /* @noEscape */ $block->getFilterData($partner['return_policy']);?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
    <?php if($analyticStatus && $analyticId) {?>
        <script>
            require([
                'jquery',
                'mage/cookies'
            ], function($) {
                var analyticId = "<?= $analyticId ?>";
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                    })(window,document,'script','https://www.google-analytics.com/analytics.js','wkga');

                    wkga('create', analyticId, {'name':'seller'});
                    wkga('seller.send', 'pageview');
            });
        </script>
    <?php }?>
<?php }  ?>
