<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$sellerId = $partner->getSellerId();
$feeds = $block->getFeed();
if (empty($feeds['feed_price'])) {
    $feeds['feed_price'] = 0;
}
if (empty($feeds['feed_value'])) {
    $feeds['feed_value'] = 0;
}
if (empty($feeds['feed_quality'])) {
    $feeds['feed_quality'] = 0;
}
$widthPriceStar5 = 0;
$widthPriceStar4 = 0;
$widthPriceStar3 = 0;
$widthPriceStar2 = 0;
$widthPriceStar1 = 0;

$borderPriceStar5 = 0;
$borderPriceStar4 = 0;
$borderPriceStar3 = 0;
$borderPriceStar2 = 0;
$borderPriceStar1 = 0;
if ($feeds['feedcount']) {
    $widthPriceStar5 = ($feeds['price_star_5']*100)/$feeds['feedcount'];
    if ($widthPriceStar5) {
        $borderPriceStar5 = 3;
    }
    $widthPriceStar4 = ($feeds['price_star_4']*100)/$feeds['feedcount'];
    if ($widthPriceStar4) {
        $borderPriceStar4 = 3;
    }
    $widthPriceStar3 = ($feeds['price_star_3']*100)/$feeds['feedcount'];
    if ($widthPriceStar3) {
        $borderPriceStar3 = 3;
    }
    $widthPriceStar2 = ($feeds['price_star_2']*100)/$feeds['feedcount'];
    if ($widthPriceStar2) {
        $borderPriceStar2 = 3;
    }
    $widthPriceStar1 = ($feeds['price_star_1']*100)/$feeds['feedcount'];
    if ($widthPriceStar1) {
        $borderPriceStar1 = 3;
    }
}
$avgPriceRatingStar = round(($feeds['price']/20), 1, PHP_ROUND_HALF_UP);
$avgPriceRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgPriceRatingStar;

$widthValueStar5 = 0;
$widthValueStar4 = 0;
$widthValueStar3 = 0;
$widthValueStar2 = 0;
$widthValueStar1 = 0;

$borderValueStar5 = 0;
$borderValueStar4 = 0;
$borderValueStar3 = 0;
$borderValueStar2 = 0;
$borderValueStar1 = 0;
if ($feeds['feedcount']) {
    $widthValueStar5 = ($feeds['value_star_5']*100)/$feeds['feedcount'];
    if ($widthValueStar5) {
        $borderValueStar5 = 3;
    }
    $widthValueStar4 = ($feeds['value_star_4']*100)/$feeds['feedcount'];
    if ($widthValueStar4) {
        $borderValueStar4 = 3;
    }
    $widthValueStar3 = ($feeds['value_star_3']*100)/$feeds['feedcount'];
    if ($widthValueStar3) {
        $borderValueStar3 = 3;
    }
    $widthValueStar2 = ($feeds['value_star_2']*100)/$feeds['feedcount'];
    if ($widthValueStar2) {
        $borderValueStar2 = 3;
    }
    $widthValueStar1 = ($feeds['value_star_1']*100)/$feeds['feedcount'];
    if ($widthValueStar1) {
        $borderValueStar1 = 3;
    }
}
$avgValueRatingStar = round(($feeds['value']/20), 1, PHP_ROUND_HALF_UP);
$avgValueRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgValueRatingStar;

$widthQualityStar5 = 0;
$widthQualityStar4 = 0;
$widthQualityStar3 = 0;
$widthQualityStar2 = 0;
$widthQualityStar1 = 0;

$borderQualityStar5 = 0;
$borderQualityStar4 = 0;
$borderQualityStar3 = 0;
$borderQualityStar2 = 0;
$borderQualityStar1 = 0;
if ($feeds['feedcount']) {
    $widthQualityStar5 = ($feeds['quality_star_5']*100)/$feeds['feedcount'];
    if ($widthQualityStar5) {
        $borderQualityStar5 = 3;
    }
    $widthQualityStar4 = ($feeds['quality_star_4']*100)/$feeds['feedcount'];
    if ($widthQualityStar4) {
        $borderQualityStar4 = 3;
    }
    $widthQualityStar3 = ($feeds['quality_star_3']*100)/$feeds['feedcount'];
    if ($widthQualityStar3) {
        $borderQualityStar3 = 3;
    }
    $widthQualityStar2 = ($feeds['quality_star_2']*100)/$feeds['feedcount'];
    if ($widthQualityStar2) {
        $borderQualityStar2 = 3;
    }
    $widthQualityStar1 = ($feeds['quality_star_1']*100)/$feeds['feedcount'];
    if ($widthQualityStar1) {
        $borderQualityStar1 = 3;
    }
}
$avgQualityRatingStar = round(($feeds['quality']/20), 1, PHP_ROUND_HALF_UP);
$avgQualityRatingClass = "wk-mp-rating-icon wk-mp-star".(int)$avgQualityRatingStar;

$feedbackUrl = $helper->getRewriteUrl('stylist/seller/feedback/'.$shopUrl);

$totalRatingStar = $helper->getSelleRating($sellerId);
$ratingClass = "wk-mp-rating-icon wk-mp-star".(int)$totalRatingStar;
?>
<div class="wk-mp-rating-block" id="rating">
    <div class="wk-mp-rating-reviews">
        <?php
        foreach ($block->getFeedCollection() as $keyed) {
            $feedcustomer = $block->Customer->load($keyed['buyer_id']);
            $name = $keyed['feed_nickname'];
            $feedDateTime= strtotime($keyed['created_at']);
            $feedDate = date('F Y', $feedDateTime);
            $feedPrice = round(($keyed['feed_price']/20), 1, PHP_ROUND_HALF_UP);
            $feedValue = round(($keyed['feed_value']/20), 1, PHP_ROUND_HALF_UP);
            $feedQuality = round(($keyed['feed_quality']/20), 1, PHP_ROUND_HALF_UP);
            ?>
            <div class="wk-mp-rating-row">
                <div class="wk-mp-rating-customer-row">
                    <div class="wk-mp-rating-customer-avatar">
                        <?php
                            $nameArray = preg_split("/[\s,_-]+/", $name);
                            $nameAcronym = "";
                            foreach ($nameArray as $w) {
                                $nameAcronym .= $w[0];
                            }
                        ?>
                        <span><?php echo $nameAcronym; ?></span>
                    </div>
                    <div class="wk-mp-rating-customer-info">
                        <strong><?= $escaper->escapeHtml($name)?></strong>
                        <span><?= $escaper->escapeHtml($feedDate)?></span>
                    </div>
                </div>
                <div class="wk-mp-rating-summary-container">
                    <p>"<?= $escaper->escapeHtml($keyed['feed_review'])?>"</p>
                </div>
            </div>
            <?php
        } ?>
        <div class="wk-mp-collection-view-btn">
            <a href="<?= $escaper->escapeUrl($feedbackUrl)?>" title="<?= $escaper->escapeHtml(__('View All Reviews'))?>" target="blank">
                <?= $escaper->escapeHtml(__('View All Reviews'))?>
            </a>
        </div>
    </div>
    <div class="wk-mp-rating-leave-review">
        <div class="wk-mp-rating-avg">
            <div class="wk-mp-rating-avg-count <?= $escaper->escapeHtml($ratingClass)?>">
                <?= $escaper->escapeHtml($totalRatingStar); ?>
            </div>
            <div class="wk-mp-rating-avg-txt">
                <?= $escaper->escapeHtml(__('Average Rating (%1)', $feeds['feedcount']))?>
            </div>
            <div class="wk-mp-rating-avg-txt">
                <?php
                $review_percentage = (($totalRatingStar*100)/5);
                /* @noEscape */ echo $review_percentage."% ".__('positive feedback');
                ?>
            </div>
            <div class="wk-mp-collection-view-btn">
                <a href="<?= /* @noEscape */ $feedbackUrl.'#customer-reviews'?>" title="<?= $escaper->escapeHtml(__('Make a Review'))?>">
                    <?= $escaper->escapeHtml(__('Write your Review'))?>
                </a>
            </div>
        </div>
    </div>
</div>
