<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_GiftCard
 */
?>
<?php /** @var $block \Amasty\GiftCard\Block\Product\View\Type\GiftCard */ ?>
<?php $product = $block->getProduct(); ?>
<!-- ko scope: 'giftCard' -->
<div class="amcard-general-container" data-bind="css: {'-visible': isContainerReady}">
    <!-- ko if: giftCardType == cardTypes.combined -->
    <div class="amcard-form-container">
        <span class="amcard-title"><?= $block->escapeHtml(__('Want to send a physical gift card or prefer to keep things digital?')) ?></span>
        <div class="amcard-flex-container -checkbox">
            <div class="amcard-checkbox-container">
                <input type="checkbox"
                       id="amcard-checkbox-physical"
                       class="amcard-checkbox"
                       data-bind="checked: isPhysicalGift, checkedValue: 2, css: {'required-entry': !currentCardType()}"/>
                <label for="amcard-checkbox-physical" class="amcard-label">
                    <span class="amcard-name"><?= $block->escapeHtml(__('Physical Gift Card')) ?></span>
                </label>
            </div>
            <div class="amcard-checkbox-container">
                <input type="checkbox"
                       id="amcard-checkbox-egift"
                       class="amcard-checkbox"
                       data-bind="checked: isEGift, checkedValue: 1, css: {'required-entry': !currentCardType()}"/>
                <label for="amcard-checkbox-egift" class="amcard-label">
                    <span class="amcard-name"><?= $block->escapeHtml(__('e-Gift Card')) ?></span>
                </label>
            </div>
        </div>
        <input type="text"
               name="am_giftcard_type"
               class="amcard-input -hidden required-entry"
               data-bind="value: currentCardType, afterRender: getGiftCardType.bind($data, $element.name)"/>
    </div>
    <!-- /ko -->
    <div class="amcard-form-container" data-bind="scope: 'price'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="amcard-form-container -interior" data-bind="scope: 'images'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="amcard-form-container">
        <span class="amcard-title amcard-title-section"><?= $block->escapeHtml(__('To')) ?>:</span>
        <div class="amcard-flex-container amcard-flex-container-fields">
            <!-- ko if: isShowField('am_giftcard_recipient_name') && (!isPhysicalGift() || isEGift()) -->
            <div class="amcard-field-container">
                <div class="amcard-field-block">
                    <input type="text"
                           class="amcard-field required-entry"
                           name="am_giftcard_recipient_name"
                           placeholder="<?= $block->escapeHtmlAttr(__('Recipient\'s Name *')) ?>"
                           data-amcard-js="field"
                           data-bind="value: getPreconfiguredValue($element.name)"/>
                </div>
            </div>
            <!-- /ko -->
            <!-- ko if: !isPhysicalGift() || isEGift() -->
            <div class="amcard-field-container">
                <div class="amcard-field-block">
                    <input type="text"
                        class="amcard-field required-entry"
                        name="am_giftcard_recipient_email"
                        placeholder="<?= $block->escapeHtmlAttr(__('Recipient\'s Email *')) ?>"
                        data-amcard-js="field"
                        data-bind="value: getPreconfiguredValue($element.name)"/>
                </div>
            </div>
            <!-- /ko -->
        </div>
        <!-- ko if: isShowField('am_giftcard_message') -->
        <div class="amcard-field-block">
            <textarea class="amcard-field"
                      name="am_giftcard_message"
                      placeholder="<?= $block->escapeHtmlAttr(__('Write a Personal Message (optional)')) ?>"
                      cols="30" rows="2"
                      data-amgiftcard-js="textarea"
                      data-amcard-js="field"
                      data-bind="value: getPreconfiguredValue($element.name)"></textarea>
            <div class="textarea-message">
                <span data-amcard-js="char-counter"></span>
                <p><?= $block->escapeHtmlAttr(__('We’ll include it on the email to your recipient')) ?></p>
            </div>
            
        </div>
        <!-- /ko -->
    </div>
    <!-- ko if: isEGift() || giftCardType == cardTypes.virtual -->
    <div class="amcard-preview-container">
        <input type="button" class="amcard-button" value="<?= $block->escapeHtmlAttr(__('Preview Gift Card')) ?>" data-bind="click: openGiftPreview"/>
        <div class="amcard-preview" data-amcard-js="preview"></div>
    </div>
    <!-- /ko -->
    <div class="amcard-form-container">
        <span class="amcard-title amcard-title-section"><?= $block->escapeHtml(__('From')) ?>:</span>
        <div class="amcard-flex-container amcard-flex-container-fields">
            <!-- ko if: isShowField('am_giftcard_sender_name') -->
            <div class="amcard-field-container">
                <div class="amcard-field-block">
                    <input type="text"
                           class="amcard-field required-entry"
                           name="am_giftcard_sender_name"
                           placeholder="<?= $block->escapeHtmlAttr(__('Your Name *')) ?>"
                           data-amcard-js="field"
                           data-bind="value: getPreconfiguredValue($element.name)"/>
                </div>
            </div>
            <!-- /ko -->
        </div>
    </div>
    <!-- ko if: isShowField('am_giftcard_date_delivery') -->
    <div class="amcard-form-container" data-bind="scope: 'datepicker'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <!-- /ko -->
</div>
<!-- /ko -->

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "datepicker": {
                    "component": "Amasty_GiftCard/js/datepicker",
                    "template": "Amasty_GiftCard/datepicker",
                    "timezones": <?= /* @noEscape */ $block->getListTimezones() ?>
                },
                "images": {
                    "component": "Amasty_GiftCard/js/images",
                    "template": "Amasty_GiftCard/images",
                    "images": <?= /* @noEscape */ $block->getImages() ?>,
                    "isCustomImageAllowed": <?= /* @noEscape */ (int)$block->getAllowUsersUploadImages() ?>,
                    "tooltip": "<?= $block->escapeHtml($block->getTooltipContent()) ?>",
                    "customImageUrl": "<?= $block->escapeUrl($block->getCustomImageUrl()) ?>"
                },
                "giftCard": {
                    "component": "Amasty_GiftCard/js/giftcard",
                    "giftCardType": "<?= /* @noEscape */ $product->getAmGiftcardType() ?>",
                    "previewUrl": "<?= $block->escapeUrl($block->getUrl('amgcard/preview/getPreviewContent')) ?>",
                    "allowedFields": <?= /* @noEscape */ $block->getAvailableOptions() ?>,
                    "preconfiguredValues": <?= /* @noEscape */ $block->getDefaultValues() ?>,
                    "customImageUrl": "<?= $block->escapeUrl($block->getCustomImageUrl()) ?>"
                }
            }
        }
    }
}
</script>
