<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_MpsellersliderTwo
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$magentoCurrentUrl = $block->getCurrentUrl();
$viewModel = $block->getViewModel();
$helper = $viewModel->getMpHelper();
/*Get current URL*/
$isPartner= $helper->isSeller();
$secure = $block->getIsSecure();

$isSellerGroup = $helper->isSellerGroupModuleInstalled();
/*Check if current customer is a seller or not*/
if ($isPartner): ?>
    <!-- if is a seller then show left link -->
    <?php if (($isSellerGroup && $helper->isAllowedAction('mpsellerslidertwo/mpslidertwo/index')) || !$isSellerGroup): ?>
        <li class="nav item
        <?= /* @noEscape */ strpos($magentoCurrentUrl, 'mpsellerslidertwo') ? "current":"";?>">
            <?php
            if (strpos($magentoCurrentUrl, 'mpsellerslidertwo')!==false) { ?>
                <strong><?= /* @noEscape */ __('Manage Slider Images') ?></strong>
    <?php   } else { ?>
                <a href="<?= /* @noEscape */
                $block->getUrl('mpsellerslidertwo/mpslidertwo/index', ['_secure' => $secure]); ?>">
                    <?= /* @noEscape */   __('Areas of Expertise') ?>
                </a>
            <?php } ?>
        </li>
    <?php endif; ?>
<?php endif; ?>
